// mockdata
export const AIRPORT_DATA =

{
  "flights": [
      {
          "flight_number": "RPA4459",
          "time": "12:17 PM",
          "type": "arrival",
          "origin_city": "New York",
          "origin": "LGA",
          "aircraft_type": "E75L",
          "registration": "N410YX",
          "gate": "",
          "status": "En Route / On Time",
          "airline": "RPA",
          "flight_time": "1h 7m",
          "diverted": false
      },
      {
          "flight_number": "JBU2786",
          "time": "12:17 PM",
          "type": "departure",
          "destination_city": "New York",
          "destination": "JFK",
          "aircraft_type": "BCS3",
          "registration": "N3241J",
          "gate": "C7",
          "status": "Taxiing / Left Gate",
          "airline": "JBU",
          "diverted": false
      },
      {
          "flight_number": "DAL2633",
          "time": "12:22 PM",
          "type": "departure",
          "destination_city": "Atlanta",
          "destination": "ATL",
          "aircraft_type": "B752",
          "registration": "N705TW",
          "gate": null,
          "status": "Taxiing / Delayed",
          "airline": "DAL",
          "diverted": false
      },
      {
          "flight_number": "N329RE",
          "time": "12:25 PM",
          "type": "departure",
          "destination_city": "Pensacola",
          "destination": "PNS",
          "aircraft_type": "SF50",
          "registration": "N329RE",
          "gate": null,
          "status": "Scheduled",
          "airline": null,
          "diverted": false
      },
      {
          "flight_number": "N45SE",
          "time": "12:27 PM",
          "type": "arrival",
          "origin_city": "Columbia",
          "origin": "CAE",
          "aircraft_type": "CL35",
          "registration": "N45SE",
          "gate": "",
          "status": "En Route",
          "airline": null,
          "flight_time": "0h 30m",
          "diverted": false
      },
      {
          "flight_number": "DAL1038",
          "time": "12:27 PM",
          "type": "departure",
          "destination_city": "Fort Lauderdale",
          "destination": "FLL",
          "aircraft_type": "A320",
          "registration": "N366NW",
          "gate": "D9",
          "status": "Scheduled",
          "airline": "DAL",
          "diverted": false
      },
      {
          "flight_number": "DAL2519",
          "time": "12:29 PM",
          "type": "departure",
          "destination_city": "Minneapolis",
          "destination": "MSP",
          "aircraft_type": "B712",
          "registration": "N944AT",
          "gate": "D5",
          "status": "Taxiing / Left Gate",
          "airline": "DAL",
          "diverted": false
      },
      {
          "flight_number": "ENY3590",
          "time": "12:29 PM",
          "type": "departure",
          "destination_city": "Washington",
          "destination": "DCA",
          "aircraft_type": "E75L",
          "registration": "N283NN",
          "gate": "C16",
          "status": "Taxiing / Left Gate",
          "airline": "ENY",
          "diverted": false
      },
      {
          "flight_number": "SWA2939",
          "time": "12:35 PM",
          "type": "departure",
          "destination_city": "Baltimore",
          "destination": "BWI",
          "aircraft_type": "B738",
          "registration": "N8503A",
          "gate": null,
          "status": "Scheduled",
          "airline": "SWA",
          "diverted": false
      },
      {
          "flight_number": "SWA1708",
          "time": "12:40 PM",
          "type": "departure",
          "destination_city": "Atlanta",
          "destination": "ATL",
          "aircraft_type": "B737",
          "registration": "N922WN",
          "gate": "A9",
          "status": "Scheduled",
          "airline": "SWA",
          "diverted": false
      },
      {
          "flight_number": "SWA3301",
          "time": "12:42 PM",
          "type": "departure",
          "destination_city": "Austin",
          "destination": "AUS",
          "aircraft_type": "B737",
          "registration": "N263WN",
          "gate": "A6",
          "status": "Scheduled / Delayed",
          "airline": "SWA",
          "diverted": false
      },
      {
          "flight_number": "EDV4911",
          "time": "12:50 PM",
          "type": "departure",
          "destination_city": "Hebron",
          "destination": "CVG",
          "aircraft_type": "CRJ9",
          "registration": "N153PQ",
          "gate": "D5",
          "status": "Scheduled",
          "airline": "EDV",
          "diverted": false
      },
      {
          "flight_number": "DAL1377",
          "time": "12:50 PM",
          "type": "departure",
          "destination_city": "Orlando",
          "destination": "MCO",
          "aircraft_type": "A320",
          "registration": "N337NW",
          "gate": "D1",
          "status": "Scheduled",
          "airline": "DAL",
          "diverted": false
      },
      {
          "flight_number": "RPA4765",
          "time": "12:51 PM",
          "type": "departure",
          "destination_city": "New York",
          "destination": "JFK",
          "aircraft_type": "E75L",
          "registration": "N445YX",
          "gate": null,
          "status": "Scheduled",
          "airline": "RPA",
          "diverted": false
      },
      {
          "flight_number": "N30M",
          "time": "12:53 PM",
          "type": "arrival",
          "origin_city": "Charlottesville",
          "origin": "CHO",
          "aircraft_type": "C525",
          "registration": "N30M",
          "gate": "",
          "status": "Scheduled",
          "airline": null,
          "flight_time": "N/A",
          "diverted": false
      },
      {
          "flight_number": "SWA1422",
          "time": "12:54 PM",
          "type": "arrival",
          "origin_city": "Nashville",
          "origin": "BNA",
          "aircraft_type": "B737",
          "registration": "N7750A",
          "gate": "",
          "status": "En Route / On Time",
          "airline": "SWA",
          "flight_time": "1h 9m",
          "diverted": false
      },
      {
          "flight_number": "N442CJ",
          "time": "01:07 PM",
          "type": "arrival",
          "origin_city": "Miami",
          "origin": "MIA",
          "aircraft_type": "C525",
          "registration": "N442CJ",
          "gate": "",
          "status": "En Route",
          "airline": null,
          "flight_time": "2h 16m",
          "diverted": false
      },
      {
          "flight_number": "RPA5803",
          "time": "01:11 PM",
          "type": "arrival",
          "origin_city": "Orlando",
          "origin": "MCO",
          "aircraft_type": "E75L",
          "registration": "N215JQ",
          "gate": "",
          "status": "En Route / Delayed",
          "airline": "RPA",
          "flight_time": "1h 18m",
          "diverted": false
      },
      {
          "flight_number": "EJA469",
          "time": "01:12 PM",
          "type": "arrival",
          "origin_city": "Pinehurst/Southern Pines",
          "origin": null,
          "aircraft_type": "E55P",
          "registration": "N469QS",
          "gate": "",
          "status": "Scheduled",
          "airline": "EJA",
          "flight_time": "N/A",
          "diverted": false
      },
      {
          "flight_number": "SKW4153",
          "time": "01:14 PM",
          "type": "arrival",
          "origin_city": "Austin",
          "origin": "AUS",
          "aircraft_type": "E75L",
          "registration": "N294SY",
          "gate": "",
          "status": "En Route / On Time",
          "airline": "SKW",
          "flight_time": "2h 20m",
          "diverted": false
      },
      {
          "flight_number": "WUP892",
          "time": "01:16 PM",
          "type": "arrival",
          "origin_city": "Greenville",
          "origin": null,
          "aircraft_type": "B350",
          "registration": "N892UP",
          "gate": "",
          "status": "Scheduled",
          "airline": "WUP",
          "flight_time": "N/A",
          "diverted": false
      },
      {
          "flight_number": "FFT1554",
          "time": "01:18 PM",
          "type": "arrival",
          "origin_city": "Orlando",
          "origin": "MCO",
          "aircraft_type": "A21N",
          "registration": "N651FR",
          "gate": "",
          "status": "En Route / On Time",
          "airline": "FFT",
          "flight_time": "1h 15m",
          "diverted": false
      },
      {
          "flight_number": "N458BA",
          "time": "01:26 PM",
          "type": "arrival",
          "origin_city": "Asheville",
          "origin": "AVL",
          "aircraft_type": "BE55",
          "registration": "N458BA",
          "gate": "",
          "status": "En Route",
          "airline": null,
          "flight_time": "1h 10m",
          "diverted": false
      },
      {
          "flight_number": "LXJ374",
          "time": "01:37 PM",
          "type": "arrival",
          "origin_city": "Greer",
          "origin": "GSP",
          "aircraft_type": "E55P",
          "registration": "N374FX",
          "gate": "",
          "status": "Scheduled",
          "airline": "LXJ",
          "flight_time": "N/A",
          "diverted": false
      },
      {
          "flight_number": "ENY4152",
          "time": "01:38 PM",
          "type": "arrival",
          "origin_city": "Chicago",
          "origin": "ORD",
          "aircraft_type": "E170",
          "registration": "N792JB",
          "gate": "",
          "status": "En Route / On Time",
          "airline": "ENY",
          "flight_time": "1h 22m",
          "diverted": false
      },
      {
          "flight_number": "RPA3645",
          "time": "01:43 PM",
          "type": "arrival",
          "origin_city": "Washington",
          "origin": "IAD",
          "aircraft_type": "E170",
          "registration": "N648RW",
          "gate": "",
          "status": "Scheduled",
          "airline": "RPA",
          "flight_time": "N/A",
          "diverted": false
      },
      {
          "flight_number": "DAL2026",
          "time": "01:45 PM",
          "type": "arrival",
          "origin_city": "Atlanta",
          "origin": "ATL",
          "aircraft_type": "B739",
          "registration": "N945DZ",
          "gate": "",
          "status": "Scheduled",
          "airline": "DAL",
          "flight_time": "N/A",
          "diverted": false
      }
  ],
  "weather": {
      "city": "Raleigh",
      "airport_name": "Raleigh-Durham Intl, NC, US",
      "temperature": 63,
      "temperature_celsius": 17.2,
      "wind": 9,
      "wind_direction": 320,
      "wind_gusts": 19,
      "visibility": 16093,
      "raw_metar": "KRDU 161551Z 32009G19KT 10SM SCT070 17/M01 A3005 RMK AO2 SLP173 T01721011",
      "latitude": 35.8923,
      "longitude": -78.782,
      "main": "Clouds",
      "description": "scattered clouds",
      "icon": "03d"
  }
}